name: Deploy Terraform Weather API

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Zip Lambda Function
        run: zip lambda.zip index.js

     
      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

  

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
      
      - name: Deploy index.html to S3
        run: |
          aws s3 cp frontend/index.html s3://my-weather-frontend-bucket/index.html --acl public-read

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id YOUR_CLOUDFRONT_DISTRIBUTION_ID \
            --paths "/index.html"
